package com.xmheart.model;

public class XPWDoctor {

	/**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.dept_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long deptId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.duty
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String duty;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.professional_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String professionalTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.grade
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String grade;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String brief;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.intro
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String intro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String imageUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.appointment_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String appointmentUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.is_displayed
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Boolean isDisplayed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_doctor.doc_order
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Integer docOrder;
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.id
     * @return  the value of xpw_doctor.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.id
     * @param id  the value for xpw_doctor.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.name
     * @return  the value of xpw_doctor.name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.name
     * @param name  the value for xpw_doctor.name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.dept_id
     * @return  the value of xpw_doctor.dept_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.dept_id
     * @param deptId  the value for xpw_doctor.dept_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.duty
     * @return  the value of xpw_doctor.duty
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.duty
     * @param duty  the value for xpw_doctor.duty
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.professional_title
     * @return  the value of xpw_doctor.professional_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getProfessionalTitle() {
        return professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.professional_title
     * @param professionalTitle  the value for xpw_doctor.professional_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setProfessionalTitle(String professionalTitle) {
        this.professionalTitle = professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.grade
     * @return  the value of xpw_doctor.grade
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.grade
     * @param grade  the value for xpw_doctor.grade
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.brief
     * @return  the value of xpw_doctor.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.brief
     * @param brief  the value for xpw_doctor.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.intro
     * @return  the value of xpw_doctor.intro
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.intro
     * @param intro  the value for xpw_doctor.intro
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.url
     * @return  the value of xpw_doctor.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.url
     * @param url  the value for xpw_doctor.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.image_url
     * @return  the value of xpw_doctor.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.image_url
     * @param imageUrl  the value for xpw_doctor.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.appointment_url
     * @return  the value of xpw_doctor.appointment_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getAppointmentUrl() {
        return appointmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.appointment_url
     * @param appointmentUrl  the value for xpw_doctor.appointment_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setAppointmentUrl(String appointmentUrl) {
        this.appointmentUrl = appointmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.is_displayed
     * @return  the value of xpw_doctor.is_displayed
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Boolean getIsDisplayed() {
        return isDisplayed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.is_displayed
     * @param isDisplayed  the value for xpw_doctor.is_displayed
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setIsDisplayed(Boolean isDisplayed) {
        this.isDisplayed = isDisplayed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_doctor.doc_order
     * @return  the value of xpw_doctor.doc_order
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Integer getDocOrder() {
        return docOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_doctor.doc_order
     * @param docOrder  the value for xpw_doctor.doc_order
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setDocOrder(Integer docOrder) {
        this.docOrder = docOrder;
    }

    private XPWDept dept;
	public void setDept(XPWDept dept) {
		this.dept = dept;
	}
	
	public XPWDept getDept() {
		return this.dept;
	}
}