package com.xmheart.model;

import java.util.Date;

public class XPWElecNewspaper {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.years
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String years;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.times
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String times;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.page
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Byte page;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Boolean isPublished;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.download_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String downloadUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String imageUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.id
     * @return  the value of xpw_electronic_newspaper.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.id
     * @param id  the value for xpw_electronic_newspaper.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.title
     * @return  the value of xpw_electronic_newspaper.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.title
     * @param title  the value for xpw_electronic_newspaper.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.years
     * @return  the value of xpw_electronic_newspaper.years
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.years
     * @param years  the value for xpw_electronic_newspaper.years
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setYears(String years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.times
     * @return  the value of xpw_electronic_newspaper.times
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.times
     * @param times  the value for xpw_electronic_newspaper.times
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setTimes(String times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.url
     * @return  the value of xpw_electronic_newspaper.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.url
     * @param url  the value for xpw_electronic_newspaper.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.page
     * @return  the value of xpw_electronic_newspaper.page
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Byte getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.page
     * @param page  the value for xpw_electronic_newspaper.page
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setPage(Byte page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.is_published
     * @return  the value of xpw_electronic_newspaper.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Boolean getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.is_published
     * @param isPublished  the value for xpw_electronic_newspaper.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.download_url
     * @return  the value of xpw_electronic_newspaper.download_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.download_url
     * @param downloadUrl  the value for xpw_electronic_newspaper.download_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.image_url
     * @return  the value of xpw_electronic_newspaper.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.image_url
     * @param imageUrl  the value for xpw_electronic_newspaper.image_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.publish_time
     * @return  the value of xpw_electronic_newspaper.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.publish_time
     * @param publishTime  the value for xpw_electronic_newspaper.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
}