package com.xmheart.model;

import java.util.ArrayList;
import java.util.List;

public class XPWIndexExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public XPWIndexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(Integer value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(Integer value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(Integer value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(Integer value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(Integer value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(Integer value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<Integer> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<Integer> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(Integer value1, Integer value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(Integer value1, Integer value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlIsNull() {
            addCriterion("banner_image_1_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlIsNotNull() {
            addCriterion("banner_image_1_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlEqualTo(String value) {
            addCriterion("banner_image_1_url =", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlNotEqualTo(String value) {
            addCriterion("banner_image_1_url <>", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlGreaterThan(String value) {
            addCriterion("banner_image_1_url >", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_1_url >=", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlLessThan(String value) {
            addCriterion("banner_image_1_url <", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_1_url <=", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlLike(String value) {
            addCriterion("banner_image_1_url like", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlNotLike(String value) {
            addCriterion("banner_image_1_url not like", value, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlIn(List<String> values) {
            addCriterion("banner_image_1_url in", values, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlNotIn(List<String> values) {
            addCriterion("banner_image_1_url not in", values, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlBetween(String value1, String value2) {
            addCriterion("banner_image_1_url between", value1, value2, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1UrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_1_url not between", value1, value2, "bannerImage1Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlIsNull() {
            addCriterion("banner_image_1_action_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlIsNotNull() {
            addCriterion("banner_image_1_action_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlEqualTo(String value) {
            addCriterion("banner_image_1_action_url =", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlNotEqualTo(String value) {
            addCriterion("banner_image_1_action_url <>", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlGreaterThan(String value) {
            addCriterion("banner_image_1_action_url >", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_1_action_url >=", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlLessThan(String value) {
            addCriterion("banner_image_1_action_url <", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_1_action_url <=", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlLike(String value) {
            addCriterion("banner_image_1_action_url like", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlNotLike(String value) {
            addCriterion("banner_image_1_action_url not like", value, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlIn(List<String> values) {
            addCriterion("banner_image_1_action_url in", values, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlNotIn(List<String> values) {
            addCriterion("banner_image_1_action_url not in", values, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlBetween(String value1, String value2) {
            addCriterion("banner_image_1_action_url between", value1, value2, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage1ActionUrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_1_action_url not between", value1, value2, "bannerImage1ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlIsNull() {
            addCriterion("banner_image_2_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlIsNotNull() {
            addCriterion("banner_image_2_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlEqualTo(String value) {
            addCriterion("banner_image_2_url =", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlNotEqualTo(String value) {
            addCriterion("banner_image_2_url <>", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlGreaterThan(String value) {
            addCriterion("banner_image_2_url >", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_2_url >=", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlLessThan(String value) {
            addCriterion("banner_image_2_url <", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_2_url <=", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlLike(String value) {
            addCriterion("banner_image_2_url like", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlNotLike(String value) {
            addCriterion("banner_image_2_url not like", value, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlIn(List<String> values) {
            addCriterion("banner_image_2_url in", values, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlNotIn(List<String> values) {
            addCriterion("banner_image_2_url not in", values, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlBetween(String value1, String value2) {
            addCriterion("banner_image_2_url between", value1, value2, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2UrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_2_url not between", value1, value2, "bannerImage2Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlIsNull() {
            addCriterion("banner_image_2_action_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlIsNotNull() {
            addCriterion("banner_image_2_action_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlEqualTo(String value) {
            addCriterion("banner_image_2_action_url =", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlNotEqualTo(String value) {
            addCriterion("banner_image_2_action_url <>", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlGreaterThan(String value) {
            addCriterion("banner_image_2_action_url >", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_2_action_url >=", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlLessThan(String value) {
            addCriterion("banner_image_2_action_url <", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_2_action_url <=", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlLike(String value) {
            addCriterion("banner_image_2_action_url like", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlNotLike(String value) {
            addCriterion("banner_image_2_action_url not like", value, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlIn(List<String> values) {
            addCriterion("banner_image_2_action_url in", values, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlNotIn(List<String> values) {
            addCriterion("banner_image_2_action_url not in", values, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlBetween(String value1, String value2) {
            addCriterion("banner_image_2_action_url between", value1, value2, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage2ActionUrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_2_action_url not between", value1, value2, "bannerImage2ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlIsNull() {
            addCriterion("banner_image_3_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlIsNotNull() {
            addCriterion("banner_image_3_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlEqualTo(String value) {
            addCriterion("banner_image_3_url =", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlNotEqualTo(String value) {
            addCriterion("banner_image_3_url <>", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlGreaterThan(String value) {
            addCriterion("banner_image_3_url >", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_3_url >=", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlLessThan(String value) {
            addCriterion("banner_image_3_url <", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_3_url <=", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlLike(String value) {
            addCriterion("banner_image_3_url like", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlNotLike(String value) {
            addCriterion("banner_image_3_url not like", value, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlIn(List<String> values) {
            addCriterion("banner_image_3_url in", values, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlNotIn(List<String> values) {
            addCriterion("banner_image_3_url not in", values, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlBetween(String value1, String value2) {
            addCriterion("banner_image_3_url between", value1, value2, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3UrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_3_url not between", value1, value2, "bannerImage3Url");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlIsNull() {
            addCriterion("banner_image_3_action_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlIsNotNull() {
            addCriterion("banner_image_3_action_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlEqualTo(String value) {
            addCriterion("banner_image_3_action_url =", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlNotEqualTo(String value) {
            addCriterion("banner_image_3_action_url <>", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlGreaterThan(String value) {
            addCriterion("banner_image_3_action_url >", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_image_3_action_url >=", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlLessThan(String value) {
            addCriterion("banner_image_3_action_url <", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlLessThanOrEqualTo(String value) {
            addCriterion("banner_image_3_action_url <=", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlLike(String value) {
            addCriterion("banner_image_3_action_url like", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlNotLike(String value) {
            addCriterion("banner_image_3_action_url not like", value, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlIn(List<String> values) {
            addCriterion("banner_image_3_action_url in", values, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlNotIn(List<String> values) {
            addCriterion("banner_image_3_action_url not in", values, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlBetween(String value1, String value2) {
            addCriterion("banner_image_3_action_url between", value1, value2, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerImage3ActionUrlNotBetween(String value1, String value2) {
            addCriterion("banner_image_3_action_url not between", value1, value2, "bannerImage3ActionUrl");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleIsNull() {
            addCriterion("banner_article_1_title is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleIsNotNull() {
            addCriterion("banner_article_1_title is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleEqualTo(String value) {
            addCriterion("banner_article_1_title =", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleNotEqualTo(String value) {
            addCriterion("banner_article_1_title <>", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleGreaterThan(String value) {
            addCriterion("banner_article_1_title >", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_1_title >=", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleLessThan(String value) {
            addCriterion("banner_article_1_title <", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleLessThanOrEqualTo(String value) {
            addCriterion("banner_article_1_title <=", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleLike(String value) {
            addCriterion("banner_article_1_title like", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleNotLike(String value) {
            addCriterion("banner_article_1_title not like", value, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleIn(List<String> values) {
            addCriterion("banner_article_1_title in", values, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleNotIn(List<String> values) {
            addCriterion("banner_article_1_title not in", values, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleBetween(String value1, String value2) {
            addCriterion("banner_article_1_title between", value1, value2, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TitleNotBetween(String value1, String value2) {
            addCriterion("banner_article_1_title not between", value1, value2, "bannerArticle1Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlIsNull() {
            addCriterion("banner_article_1_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlIsNotNull() {
            addCriterion("banner_article_1_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlEqualTo(String value) {
            addCriterion("banner_article_1_url =", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlNotEqualTo(String value) {
            addCriterion("banner_article_1_url <>", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlGreaterThan(String value) {
            addCriterion("banner_article_1_url >", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_1_url >=", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlLessThan(String value) {
            addCriterion("banner_article_1_url <", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_article_1_url <=", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlLike(String value) {
            addCriterion("banner_article_1_url like", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlNotLike(String value) {
            addCriterion("banner_article_1_url not like", value, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlIn(List<String> values) {
            addCriterion("banner_article_1_url in", values, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlNotIn(List<String> values) {
            addCriterion("banner_article_1_url not in", values, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlBetween(String value1, String value2) {
            addCriterion("banner_article_1_url between", value1, value2, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1UrlNotBetween(String value1, String value2) {
            addCriterion("banner_article_1_url not between", value1, value2, "bannerArticle1Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefIsNull() {
            addCriterion("banner_article_1_brief is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefIsNotNull() {
            addCriterion("banner_article_1_brief is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefEqualTo(String value) {
            addCriterion("banner_article_1_brief =", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefNotEqualTo(String value) {
            addCriterion("banner_article_1_brief <>", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefGreaterThan(String value) {
            addCriterion("banner_article_1_brief >", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_1_brief >=", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefLessThan(String value) {
            addCriterion("banner_article_1_brief <", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefLessThanOrEqualTo(String value) {
            addCriterion("banner_article_1_brief <=", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefLike(String value) {
            addCriterion("banner_article_1_brief like", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefNotLike(String value) {
            addCriterion("banner_article_1_brief not like", value, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefIn(List<String> values) {
            addCriterion("banner_article_1_brief in", values, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefNotIn(List<String> values) {
            addCriterion("banner_article_1_brief not in", values, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefBetween(String value1, String value2) {
            addCriterion("banner_article_1_brief between", value1, value2, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1BriefNotBetween(String value1, String value2) {
            addCriterion("banner_article_1_brief not between", value1, value2, "bannerArticle1Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagIsNull() {
            addCriterion("banner_article_1_tag is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagIsNotNull() {
            addCriterion("banner_article_1_tag is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagEqualTo(String value) {
            addCriterion("banner_article_1_tag =", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagNotEqualTo(String value) {
            addCriterion("banner_article_1_tag <>", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagGreaterThan(String value) {
            addCriterion("banner_article_1_tag >", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_1_tag >=", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagLessThan(String value) {
            addCriterion("banner_article_1_tag <", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagLessThanOrEqualTo(String value) {
            addCriterion("banner_article_1_tag <=", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagLike(String value) {
            addCriterion("banner_article_1_tag like", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagNotLike(String value) {
            addCriterion("banner_article_1_tag not like", value, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagIn(List<String> values) {
            addCriterion("banner_article_1_tag in", values, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagNotIn(List<String> values) {
            addCriterion("banner_article_1_tag not in", values, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagBetween(String value1, String value2) {
            addCriterion("banner_article_1_tag between", value1, value2, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle1TagNotBetween(String value1, String value2) {
            addCriterion("banner_article_1_tag not between", value1, value2, "bannerArticle1Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleIsNull() {
            addCriterion("banner_article_2_title is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleIsNotNull() {
            addCriterion("banner_article_2_title is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleEqualTo(String value) {
            addCriterion("banner_article_2_title =", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleNotEqualTo(String value) {
            addCriterion("banner_article_2_title <>", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleGreaterThan(String value) {
            addCriterion("banner_article_2_title >", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_2_title >=", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleLessThan(String value) {
            addCriterion("banner_article_2_title <", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleLessThanOrEqualTo(String value) {
            addCriterion("banner_article_2_title <=", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleLike(String value) {
            addCriterion("banner_article_2_title like", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleNotLike(String value) {
            addCriterion("banner_article_2_title not like", value, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleIn(List<String> values) {
            addCriterion("banner_article_2_title in", values, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleNotIn(List<String> values) {
            addCriterion("banner_article_2_title not in", values, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleBetween(String value1, String value2) {
            addCriterion("banner_article_2_title between", value1, value2, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TitleNotBetween(String value1, String value2) {
            addCriterion("banner_article_2_title not between", value1, value2, "bannerArticle2Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlIsNull() {
            addCriterion("banner_article_2_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlIsNotNull() {
            addCriterion("banner_article_2_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlEqualTo(String value) {
            addCriterion("banner_article_2_url =", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlNotEqualTo(String value) {
            addCriterion("banner_article_2_url <>", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlGreaterThan(String value) {
            addCriterion("banner_article_2_url >", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_2_url >=", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlLessThan(String value) {
            addCriterion("banner_article_2_url <", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_article_2_url <=", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlLike(String value) {
            addCriterion("banner_article_2_url like", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlNotLike(String value) {
            addCriterion("banner_article_2_url not like", value, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlIn(List<String> values) {
            addCriterion("banner_article_2_url in", values, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlNotIn(List<String> values) {
            addCriterion("banner_article_2_url not in", values, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlBetween(String value1, String value2) {
            addCriterion("banner_article_2_url between", value1, value2, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2UrlNotBetween(String value1, String value2) {
            addCriterion("banner_article_2_url not between", value1, value2, "bannerArticle2Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefIsNull() {
            addCriterion("banner_article_2_brief is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefIsNotNull() {
            addCriterion("banner_article_2_brief is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefEqualTo(String value) {
            addCriterion("banner_article_2_brief =", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefNotEqualTo(String value) {
            addCriterion("banner_article_2_brief <>", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefGreaterThan(String value) {
            addCriterion("banner_article_2_brief >", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_2_brief >=", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefLessThan(String value) {
            addCriterion("banner_article_2_brief <", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefLessThanOrEqualTo(String value) {
            addCriterion("banner_article_2_brief <=", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefLike(String value) {
            addCriterion("banner_article_2_brief like", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefNotLike(String value) {
            addCriterion("banner_article_2_brief not like", value, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefIn(List<String> values) {
            addCriterion("banner_article_2_brief in", values, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefNotIn(List<String> values) {
            addCriterion("banner_article_2_brief not in", values, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefBetween(String value1, String value2) {
            addCriterion("banner_article_2_brief between", value1, value2, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2BriefNotBetween(String value1, String value2) {
            addCriterion("banner_article_2_brief not between", value1, value2, "bannerArticle2Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagIsNull() {
            addCriterion("banner_article_2_tag is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagIsNotNull() {
            addCriterion("banner_article_2_tag is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagEqualTo(String value) {
            addCriterion("banner_article_2_tag =", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagNotEqualTo(String value) {
            addCriterion("banner_article_2_tag <>", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagGreaterThan(String value) {
            addCriterion("banner_article_2_tag >", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_2_tag >=", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagLessThan(String value) {
            addCriterion("banner_article_2_tag <", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagLessThanOrEqualTo(String value) {
            addCriterion("banner_article_2_tag <=", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagLike(String value) {
            addCriterion("banner_article_2_tag like", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagNotLike(String value) {
            addCriterion("banner_article_2_tag not like", value, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagIn(List<String> values) {
            addCriterion("banner_article_2_tag in", values, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagNotIn(List<String> values) {
            addCriterion("banner_article_2_tag not in", values, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagBetween(String value1, String value2) {
            addCriterion("banner_article_2_tag between", value1, value2, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle2TagNotBetween(String value1, String value2) {
            addCriterion("banner_article_2_tag not between", value1, value2, "bannerArticle2Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleIsNull() {
            addCriterion("banner_article_3_title is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleIsNotNull() {
            addCriterion("banner_article_3_title is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleEqualTo(String value) {
            addCriterion("banner_article_3_title =", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleNotEqualTo(String value) {
            addCriterion("banner_article_3_title <>", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleGreaterThan(String value) {
            addCriterion("banner_article_3_title >", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_3_title >=", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleLessThan(String value) {
            addCriterion("banner_article_3_title <", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleLessThanOrEqualTo(String value) {
            addCriterion("banner_article_3_title <=", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleLike(String value) {
            addCriterion("banner_article_3_title like", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleNotLike(String value) {
            addCriterion("banner_article_3_title not like", value, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleIn(List<String> values) {
            addCriterion("banner_article_3_title in", values, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleNotIn(List<String> values) {
            addCriterion("banner_article_3_title not in", values, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleBetween(String value1, String value2) {
            addCriterion("banner_article_3_title between", value1, value2, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TitleNotBetween(String value1, String value2) {
            addCriterion("banner_article_3_title not between", value1, value2, "bannerArticle3Title");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlIsNull() {
            addCriterion("banner_article_3_url is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlIsNotNull() {
            addCriterion("banner_article_3_url is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlEqualTo(String value) {
            addCriterion("banner_article_3_url =", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlNotEqualTo(String value) {
            addCriterion("banner_article_3_url <>", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlGreaterThan(String value) {
            addCriterion("banner_article_3_url >", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_3_url >=", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlLessThan(String value) {
            addCriterion("banner_article_3_url <", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlLessThanOrEqualTo(String value) {
            addCriterion("banner_article_3_url <=", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlLike(String value) {
            addCriterion("banner_article_3_url like", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlNotLike(String value) {
            addCriterion("banner_article_3_url not like", value, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlIn(List<String> values) {
            addCriterion("banner_article_3_url in", values, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlNotIn(List<String> values) {
            addCriterion("banner_article_3_url not in", values, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlBetween(String value1, String value2) {
            addCriterion("banner_article_3_url between", value1, value2, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3UrlNotBetween(String value1, String value2) {
            addCriterion("banner_article_3_url not between", value1, value2, "bannerArticle3Url");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefIsNull() {
            addCriterion("banner_article_3_brief is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefIsNotNull() {
            addCriterion("banner_article_3_brief is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefEqualTo(String value) {
            addCriterion("banner_article_3_brief =", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefNotEqualTo(String value) {
            addCriterion("banner_article_3_brief <>", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefGreaterThan(String value) {
            addCriterion("banner_article_3_brief >", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_3_brief >=", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefLessThan(String value) {
            addCriterion("banner_article_3_brief <", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefLessThanOrEqualTo(String value) {
            addCriterion("banner_article_3_brief <=", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefLike(String value) {
            addCriterion("banner_article_3_brief like", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefNotLike(String value) {
            addCriterion("banner_article_3_brief not like", value, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefIn(List<String> values) {
            addCriterion("banner_article_3_brief in", values, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefNotIn(List<String> values) {
            addCriterion("banner_article_3_brief not in", values, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefBetween(String value1, String value2) {
            addCriterion("banner_article_3_brief between", value1, value2, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3BriefNotBetween(String value1, String value2) {
            addCriterion("banner_article_3_brief not between", value1, value2, "bannerArticle3Brief");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagIsNull() {
            addCriterion("banner_article_3_tag is null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagIsNotNull() {
            addCriterion("banner_article_3_tag is not null");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagEqualTo(String value) {
            addCriterion("banner_article_3_tag =", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagNotEqualTo(String value) {
            addCriterion("banner_article_3_tag <>", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagGreaterThan(String value) {
            addCriterion("banner_article_3_tag >", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagGreaterThanOrEqualTo(String value) {
            addCriterion("banner_article_3_tag >=", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagLessThan(String value) {
            addCriterion("banner_article_3_tag <", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagLessThanOrEqualTo(String value) {
            addCriterion("banner_article_3_tag <=", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagLike(String value) {
            addCriterion("banner_article_3_tag like", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagNotLike(String value) {
            addCriterion("banner_article_3_tag not like", value, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagIn(List<String> values) {
            addCriterion("banner_article_3_tag in", values, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagNotIn(List<String> values) {
            addCriterion("banner_article_3_tag not in", values, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagBetween(String value1, String value2) {
            addCriterion("banner_article_3_tag between", value1, value2, "bannerArticle3Tag");
            return (Criteria) this;
        }

        public Criteria andBannerArticle3TagNotBetween(String value1, String value2) {
            addCriterion("banner_article_3_tag not between", value1, value2, "bannerArticle3Tag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table xpw_index
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xpw_index
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 17 09:46:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}