package com.xmheart.model;

import java.util.Date;

public class XPWNav {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long columnId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.child_column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long childColumnId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String columnName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.child_column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String childColumnName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.article_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String articleTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String brief;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String imgUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_nav.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.id
     * @return  the value of xpw_nav.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.id
     * @param id  the value for xpw_nav.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.column_id
     * @return  the value of xpw_nav.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.column_id
     * @param columnId  the value for xpw_nav.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.child_column_id
     * @return  the value of xpw_nav.child_column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getChildColumnId() {
        return childColumnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.child_column_id
     * @param childColumnId  the value for xpw_nav.child_column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setChildColumnId(Long childColumnId) {
        this.childColumnId = childColumnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.column_name
     * @return  the value of xpw_nav.column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.column_name
     * @param columnName  the value for xpw_nav.column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.child_column_name
     * @return  the value of xpw_nav.child_column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getChildColumnName() {
        return childColumnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.child_column_name
     * @param childColumnName  the value for xpw_nav.child_column_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setChildColumnName(String childColumnName) {
        this.childColumnName = childColumnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.article_title
     * @return  the value of xpw_nav.article_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.article_title
     * @param articleTitle  the value for xpw_nav.article_title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.brief
     * @return  the value of xpw_nav.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.brief
     * @param brief  the value for xpw_nav.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.url
     * @return  the value of xpw_nav.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.url
     * @param url  the value for xpw_nav.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.img_url
     * @return  the value of xpw_nav.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.img_url
     * @param imgUrl  the value for xpw_nav.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_nav.publish_time
     * @return  the value of xpw_nav.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_nav.publish_time
     * @param publishTime  the value for xpw_nav.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
}