package com.xmheart.model;

import java.util.Date;

public class XPWOnlineVideo {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String imgUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.video_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String videoUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String brief;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.is_pinned
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Boolean isPinned;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Boolean isPublished;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_online_video.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.id
     * @return  the value of xpw_online_video.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.id
     * @param id  the value for xpw_online_video.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.title
     * @return  the value of xpw_online_video.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.title
     * @param title  the value for xpw_online_video.title
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.url
     * @return  the value of xpw_online_video.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.url
     * @param url  the value for xpw_online_video.url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.img_url
     * @return  the value of xpw_online_video.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.img_url
     * @param imgUrl  the value for xpw_online_video.img_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.video_url
     * @return  the value of xpw_online_video.video_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.video_url
     * @param videoUrl  the value for xpw_online_video.video_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.brief
     * @return  the value of xpw_online_video.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.brief
     * @param brief  the value for xpw_online_video.brief
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.is_pinned
     * @return  the value of xpw_online_video.is_pinned
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Boolean getIsPinned() {
        return isPinned;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.is_pinned
     * @param isPinned  the value for xpw_online_video.is_pinned
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setIsPinned(Boolean isPinned) {
        this.isPinned = isPinned;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.is_published
     * @return  the value of xpw_online_video.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Boolean getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.is_published
     * @param isPublished  the value for xpw_online_video.is_published
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_online_video.publish_time
     * @return  the value of xpw_online_video.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_online_video.publish_time
     * @param publishTime  the value for xpw_online_video.publish_time
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
}