package com.xmheart.model;

public class XPWPriv {

	/**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_priv.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_priv.table_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String tableName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_priv.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long columnId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_priv.id
     * @return  the value of xpw_priv.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_priv.id
     * @param id  the value for xpw_priv.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_priv.table_name
     * @return  the value of xpw_priv.table_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_priv.table_name
     * @param tableName  the value for xpw_priv.table_name
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_priv.column_id
     * @return  the value of xpw_priv.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_priv.column_id
     * @param columnId  the value for xpw_priv.column_id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    private String columnName;
	
	public void setColumnName(String columnName) {
	    this.columnName = columnName;
	}
	
    public String getColumnName() {
        return columnName;
    }
}