package com.xmheart.model;

public class XPWUser {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_user.id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_user.username
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_user.password
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_user.user_type
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    private Byte userType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_user.role_id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_user.id
     * @return  the value of xpw_user.id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_user.id
     * @param id  the value for xpw_user.id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_user.username
     * @return  the value of xpw_user.username
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_user.username
     * @param username  the value for xpw_user.username
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_user.password
     * @return  the value of xpw_user.password
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_user.password
     * @param password  the value for xpw_user.password
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_user.user_type
     * @return  the value of xpw_user.user_type
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_user.user_type
     * @param userType  the value for xpw_user.user_type
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_user.role_id
     * @return  the value of xpw_user.role_id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_user.role_id
     * @param roleId  the value for xpw_user.role_id
     * @mbg.generated  Thu Dec 21 15:09:25 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        return "XPWUser [id=" + id + ", username=" + username + ", password=" + password + ", userType=" + userType
                + ", roleId=" + roleId + "]";
    }
    
    private String roleName;

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    
}