package com.xmheart.model;

public class XPWXTIndex {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_1_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage1Url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_1_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage1ActionUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_2_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage2Url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_2_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage2ActionUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_3_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage3Url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_xtindex.banner_image_3_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    private String bannerImage3ActionUrl;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.id
     * @return  the value of xpw_xtindex.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.id
     * @param id  the value for xpw_xtindex.id
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_1_url
     * @return  the value of xpw_xtindex.banner_image_1_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage1Url() {
        return bannerImage1Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_1_url
     * @param bannerImage1Url  the value for xpw_xtindex.banner_image_1_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage1Url(String bannerImage1Url) {
        this.bannerImage1Url = bannerImage1Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_1_action_url
     * @return  the value of xpw_xtindex.banner_image_1_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage1ActionUrl() {
        return bannerImage1ActionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_1_action_url
     * @param bannerImage1ActionUrl  the value for xpw_xtindex.banner_image_1_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage1ActionUrl(String bannerImage1ActionUrl) {
        this.bannerImage1ActionUrl = bannerImage1ActionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_2_url
     * @return  the value of xpw_xtindex.banner_image_2_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage2Url() {
        return bannerImage2Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_2_url
     * @param bannerImage2Url  the value for xpw_xtindex.banner_image_2_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage2Url(String bannerImage2Url) {
        this.bannerImage2Url = bannerImage2Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_2_action_url
     * @return  the value of xpw_xtindex.banner_image_2_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage2ActionUrl() {
        return bannerImage2ActionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_2_action_url
     * @param bannerImage2ActionUrl  the value for xpw_xtindex.banner_image_2_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage2ActionUrl(String bannerImage2ActionUrl) {
        this.bannerImage2ActionUrl = bannerImage2ActionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_3_url
     * @return  the value of xpw_xtindex.banner_image_3_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage3Url() {
        return bannerImage3Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_3_url
     * @param bannerImage3Url  the value for xpw_xtindex.banner_image_3_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage3Url(String bannerImage3Url) {
        this.bannerImage3Url = bannerImage3Url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_xtindex.banner_image_3_action_url
     * @return  the value of xpw_xtindex.banner_image_3_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public String getBannerImage3ActionUrl() {
        return bannerImage3ActionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_xtindex.banner_image_3_action_url
     * @param bannerImage3ActionUrl  the value for xpw_xtindex.banner_image_3_action_url
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    public void setBannerImage3ActionUrl(String bannerImage3ActionUrl) {
        this.bannerImage3ActionUrl = bannerImage3ActionUrl;
    }
}