package com.xmheart.mapper;

import com.xmheart.model.XPWRole;
import com.xmheart.model.XPWRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface XPWRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    long countByExample(XPWRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    int deleteByExample(XPWRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    @Delete({ "delete from xpw_role", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    @Insert({ "insert into xpw_role (name, priv_ids)",
            "values (#{name,jdbcType=VARCHAR}, #{privIds,jdbcType=VARCHAR})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(XPWRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    int insertSelective(XPWRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    List<XPWRole> selectByExample(XPWRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    @Select({ "select", "id, name, priv_ids", "from xpw_role", "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.xmheart.mapper.XPWRoleMapper.BaseResultMap")
    XPWRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") XPWRole record, @Param("example") XPWRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    int updateByExample(@Param("record") XPWRole record, @Param("example") XPWRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    int updateByPrimaryKeySelective(XPWRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_role
     * @mbg.generated  Sat Jan 27 17:07:32 CST 2018
     */
    @Update({ "update xpw_role", "set name = #{name,jdbcType=VARCHAR},", "priv_ids = #{privIds,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(XPWRole record);
}