package com.xmheart.mapper;

import com.xmheart.model.XPWUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import com.xmheart.model.XPWUserRole;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.SelectKey;

public interface XPWUserRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    long countByExample(XPWUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    int deleteByExample(XPWUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    @Delete({ "delete from xpw_user_role", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    @Insert({ "insert into xpw_user_role (user_id, role_id)",
            "values (#{userId,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(XPWUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    int insertSelective(XPWUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    List<XPWUserRole> selectByExample(XPWUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    @Select({ "select", "id, user_id, role_id", "from xpw_user_role", "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.xmheart.mapper.XPWUserRoleMapper.BaseResultMap")
    XPWUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") XPWUserRole record, @Param("example") XPWUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    int updateByExample(@Param("record") XPWUserRole record, @Param("example") XPWUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    int updateByPrimaryKeySelective(XPWUserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_user_role
     * @mbg.generated  Tue Nov 07 11:43:44 CST 2017
     */
    @Update({ "update xpw_user_role", "set user_id = #{userId,jdbcType=BIGINT},", "role_id = #{roleId,jdbcType=BIGINT}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(XPWUserRole record);
}